### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hitaspdotnet** [pveller/ecommerce-chatbot#2]
`Collecting data for the products index
TypeError: Cannot convert undefined or null to object
    at _.chain.map.filter.flatMap.mod (..\ecommerce-chatbot-master\indexes\populate.js:64:40)
    at arrayMap (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:660:23)
    at map (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:9571:14)
    at Function.flatMap (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:9274:26)
    at ..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:4379:28
    at arrayReduce (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:704:21)
    at baseWrapperValue (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:4378:14)
    at LodashWrapper.wrapperValue (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:9067:14)
    at LazyWrapper.lazyValue [as value] (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:1864:36)
    at baseWrapperValue (..\ecommerce-chatbot-master\node_modules\lodash\lodash.js:4376:25)`

Hi, I do all steps. Anything be done. But have this problem with attaching Indexes. Whats this Master @pveller

**Comment by pveller** [comment]
I wonder if you provided the `MOLTIN_PUBLIC_ID` and `MOLTIN_SECRET_KEY` environment variables. If you didn't, Moltin would connect you to their default product catalog and I don't think those products have `color` and `size` modifiers and that would likely result in the error that you are seeing. 

To make sure you are connecting to your store with Adventure Works and not the default store, you can run the script with the environment variables on the command line:

```bash
$ MOLTIN_PUBLIC_ID=<your-id> MOLTIN_SECRET_KEY=<your-key> node indexes/populate.js
```

**Comment by siddhantsorann** [comment]
TypeError: Cannot read property 'length' of undefined
    at a.Authenticate (/home/siddhant/PROJECT/adventureworks-moltin/node_modules/moltin/dist/moltin.nodejs.min.js:2:2213)
    at Promise (/home/siddhant/PROJECT/adventureworks-moltin/promisify-moltin.js:30:20)
    at new Promise (<anonymous>)
    at Object.Create (/home/siddhant/PROJECT/adventureworks-moltin/promisify-moltin.js:29:16)
    at Rx.Observable.defer (/home/siddhant/PROJECT/adventureworks-moltin/categories.js:22:73)
    at tryCatcher (/home/siddhant/PROJECT/adventureworks-moltin/node_modules/rx/dist/rx.js:63:31)
    at Defer.subscribeCore (/home/siddhant/PROJECT/adventureworks-moltin/node_modules/rx/dist/rx.js:2536:37)
    at Defer.tryCatcher (/home/siddhant/PROJECT/adventureworks-moltin/node_modules/rx/dist/rx.js:63:31)
    at Rx.internals.ScheduledItem.setDisposable [as action] (/home/siddhant/PROJECT/adventureworks-moltin/node_modules/rx/dist/rx.js:2082:46)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (/home/siddhant/PROJECT/adventureworks-moltin/node_modules/rx/dist/rx.js:896:33)

Hi, I'm getting the above error while running the app.js and pointing to the Adventure Works Scipts. How can i move forward? @pveller

**Comment by pveller** [comment]
Did you get it working? I just pushed the update to the Adventure Works import scripts (using Moltin API v2) and the bot. Everything seems to work. I will close the issue but feel free to post new one if something doesn't work still.
